version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-image
    versions:
    - 2.8.0
  - dependency-name: gatsby
    versions:
    - 2.29.3
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.8.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.11.2
  - dependency-name: gatsby-plugin-typography
    versions:
    - 2.9.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.9.0
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: elliptic
    versions:
    - 6.5.3
